---
services:
  database:
    image: postgres:16
    container_name: pos-server-db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s  

volumes:
  dbdata:
    name: pos_db_volume
