---
services:
  server:
    image: kevharv/pos-server
    build: .
    container_name: pos-server
    env_file:
      - pos.env
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: pos-server-db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    env_file:
      - db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s  

volumes:
  dbdata:
    name: pos_db_volume
