---
services:
  server:
    build: .
    container_name: pos-server
    env_file: pos.env
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/healthz", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: pos-server-db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    env_file:
      - db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "pos-server"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s  

volumes:
  dbdata:
    name: pos_db_volume
