FROM debian:12 AS builder

LABEL app.name="POS Server"
LABEL app.version="0.1.0"

ARG GO_VERSION=1.21

# Install Go
# Compile program
# Copy to runner
# Install curl (healthcheck)
# Declare ports
# Set entrypoint